development:
  host: fts.locomotive.dev
  email: jloosfelt@gmail.com
  password: tagada1
staging:
  host: staging.example.com
  email: john@doe.net
  password: easyone
production:
  host: www.example.com
  email: john@doe.net
  password: easyone
