site:
  name: fts

  locales: [fr, en]

  seo_title: FTS
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
  - "index": # page path (the template can edited here app/views/pages/index.liquid)
      title: "Accueil"
      published: true
      seo_title: "Accueil"
      translations:
        en:
          title: "Home page"
          seo_title: "Accueil"
  - "societe":
      title: "La société"
      meta_keywords: "Test fr"
      meta_description: "La société"
      published: true
      seo_title: "Société"
      listed: true
      translations:
        en:
          slug: "urldelacompany"
          title: "Companyrr"
          seo_title: "Companyee"
          meta_keywords: "Test en"
          meta_description: "The company"
  - "recrutement":
      title: "Recrutement"
      meta_keywords: "Recrutement"
      meta_description: "Recrutement"
      published: true
      seo_title: "Recrutement"
      listed: true
      translations:
        en:
          slug: "recruitment"
          title: "Recruitment"
          seo_title: "Recruitment"
          meta_keywords: "Recruitment"
          meta_description: "Recruitment"
  - "crm360":
      title: "crm360"
      meta_keywords: "crm360"
      meta_description: "crm360"
      published: true
      seo_title: "crm360"
      listed: true
      translations:
        en:
          slug: "crm360"
          title: "crm360"
          seo_title: "crm360"
          meta_keywords: "crm360"
          meta_description: "crm360"
  - "clients":
      meta_keywords: "Client fr"
      meta_description: "Clients"
      published: true
      seo_title: "Clients"
      title: Clients
      listed: true
      translations:
        en:
          title: "Customers"
          seo_title: "Customers"
          meta_keywords: "Customers en"
          meta_description: "Customers"
  - clients/content_type_template:
      published: true
      title: Reference Template
      listed: true
      model: customers
      templatized: true
      translations:
        en:
          title: Reference Template
  - "partenaires":
      meta_keywords: "partenaires"
      meta_description: "Partenaires"
      published: true
      seo_title: "Partenaires"
      title: "Partenaires"
      listed: true
      translations:
        en:
          title: "Partners"
          seo_title: "Partners"
          meta_keywords: "Partners"
          meta_description: "Partners"
  - "equipe":
      meta_keywords: "L'équipe"
      meta_description: "L'équipe"
      published: true
      seo_title: "L'équipe"
      title: "L'équipe"
      listed: true
      translations:
        en:
          title: "The team"
          seo_title: "team"
          meta_keywords: "Team"
          meta_description: "The team"
  - "404":
      title: "Page not found"